Refactored Module 8 notebooks
Add refactored module 8 notebooks.
Updates for tensorflow, sklearn.metrics, plt.show(), `lr` deprecation, ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported and many others
Memory optimisation for 4GB for ML graphics
AttributeError: 'Sequential' object has no attribute 'predict_proba'